# Generated by Django 2.0.7 on 2021-03-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='courses',
            new_name='Course',
        ),
    ]
